### ISSUE TITLE
VM Password

### ISSUE THREAD

**Issue by RecklessAbandon21** [lorenzoinvidia/DNS-Kaminsky-Attack#1]
Hello, 

Thank you for all your work on this. I was able to download the VM but cant seem to login. I am trying to use the VM and code for a Computer Security Assignment. Any help with this and/or more information on how to set up the vulnerability would be greatly appreciated! 

Thank you again.

**Comment by m4ttless** [comment]
Hello, 

thanks for the feedback, I forgot to list the vm creds. By the way, I've just updated the Readme.

Lorenzo

**Comment by RecklessAbandon21** [comment]
You are a rockstar!!! Thank you so much!
